name: mealsapp
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.27.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animator: null
  cupertino_icons: null
  dartz: null
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: null
  flutter_native_splash: null
  flutter_screenutil: ^5.9.3
  flutter_svg: null
  go_router: ^15.0.0
  google_fonts: null
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/packpic.png
    - assets/images/cover.svg
    - assets/icons/
    - assets/lottie/
    - assets/lang/
